### ISSUE TITLE
pNovo and search parameters

### ISSUE THREAD

**Issue by lutfia95** [denisbeslic/denovopipeline#6]
Hey Denis, 

Thank you very much for providing the pipeline! I have couple of `*.mgf`files and trying to run the different de-novo algorithms of them. Regarding the de-novo algorithms, I have couple of questions: 

- How did you use `pNovo`? I installed it from the `pfind` website and the installation worked as usual, after opening the tool (`pNovo3_Search.exe`) I tried to run small toy example, I exactly did the same steps as in the user guide from `pFind` by choosing the input file and selecting the output dir path (all parameters are kept as default), after couple of seconds the progress output window shown that the process is completed but the search button still loading for couple of hours without writing any results (only empty results files e.g. `result.res`….etc.). I tested the tool with `DeNovoGUI` and everything worked very well and fast, but the output file is only the `pNovo.res`, which contains all searching result. Your pipeline is expecting the file `result.res`, which records the top-one PSM per spectrum. Is there any way to filter out the `pNovo.res` or to use it in your pipeline? 
-  As I am using different files, there are different search parameters/modifications. By running `Novor`, `Casanovo` and `pNovo3`(using `DeNovoGUI`), I had no problem with selecting these parameters.  Is there any way to set parameters in `SMSNet` and `DeepNovo`? In `PointNovo` should I just change the parameters in `resources/PointNovo/config.py`? 

Best,

**Comment by denisbeslic** [comment]
Hey Ahmad,
Thanks for using the pipeline.

-  I used the official pNovo GUI (v.3.1.3) from the pfind website. I remember I had similar problems with pNovo. In my case, I had to fix the header of the mgf file. I would suggest you try to simplify your header and check for the format of your mgf file. Also make sure you use the correct decimal separator in your parameters (dot or comma, depending on your system configurations).  

- I did not use the pNovo version from DeNovoGUI, since it was an older pNovo version. I did not write the pipeline expecting the pNovo input from DeNovoGUI. You could still use it, but you would need to rewrite some [parts of the script](https://github.com/denisbeslic/denovopipeline/blob/784438adf4bf663ddddc2a782c73e7bb0cc589dc/src/createsummary.py#L458C1-L504C30).

- For DeepNovo it is `data_utils.py` and for SMSNet the parameters are in `nmt/vocab`. However, it is important to mention that for the deep-learning based seq2seq models (DeepNovo, SMSNet, PointNovo, Casanovo) you cannot just select new modifications without retraining the complete model on a new dataset with the required modifications. 

Cheers,
Denis

**Comment by lutfia95** [comment]
Hey Denis, 

thank you very much for your replay. Regarding pNovo, I still have the same problem and already tested many scenarios! I used your Lys reformatted mgf file (Heavy-Chain-Lys-C-1_reformatted.mgf) which has very cleaned header. And tried to test many ways of writing parameters (used same as yours). I included an screenshot maybe you can have a look into it. 
![image](https://github.com/denisbeslic/denovopipeline/assets/62063481/8376b227-02fb-4729-9548-17ed63fa8633)
- Regarding DL Models, I have some parameters, which I could change in some of them. I will check the results afterwards and in worst case I will retrain the models. 

Best, 
Ahmad

**Comment by denisbeslic** [comment]
Hey,
it all looks correct to me. I had similar problems on my laptop, but it worked on my desktop PC.. Did pNovo3 generate any files in your case? I would suggest to contact the authors of pNovo3

**Comment by lutfia95** [comment]
Hi, 

yes I thought about that actually to use desktop (I had same issue with other stuff) but I don't have desktop atm. I already wrote the authors and hope for response. Otherwise, I will use/filter out the top10 results but I cannot use them in your pipeline due to missing values such as aaScore and others. 

Best, 
Ahmad
